package com.kadous.gestiondealer.exception;

public enum ErrorCodes {

  USERS_NOT_FOUND(1000),
  USERS_NOT_VALID(1001),
  USERS_ALREADY_IN_USE(1002),

  USER_ROLE_NOT_FOUND(2000),
  USER_ROLE_NOT_VALID(2001),
  USER_ROLE_ALREADY_IN_USE(2002),

  ROLES_NOT_FOUND(3000),
  ROLES_NOT_VALID(3001),
  ROLES_ALREADY_IN_USE(3002),

  PERMISSIONS_NOT_FOUND(4000),
  PERMISSIONS_NOT_VALID(4001),
  PERMISSIONS_NON_MODIFIABLE(4002),
 // COMMANDE_CLIENT_ALREADY_IN_USE(4003),

  USER_PERMISSION_NOT_FOUND(5000),
  USER_PERMISSION_NOT_VALID(5001),
  USER_PERMISSION_NON_MODIFIABLE(5002),
  //COMMANDE_FOURNISSEUR_ALREADY_IN_USE(5003),

  FONCTION_USER_NOT_FOUND(6000),
  FONCTION_USER_NOT_VALID(6001),
  FONCTION_USER_ALREADY_IN_USE(6002),

  FICHIER_NOT_VALID(7000),
  FICHIER_NOT_FOUND(7001),
  FICHIER__ALREADY_IN_USE(7002),

  OPERATION_TRANSACTION_NOT_FOUND(8000),
  OPERATION_TRANSACTION_NOT_VALID(8001),
  OPERATION_TRANSACTION_ALREADY_IN_USE(8002),

  USESRSKEY_NOT_FOUND(8000),
  USESRSKEY_NOT_VALID(8001),
  USESRSKEY_ALREADY_IN_USE(8002),

  ;
  
  private Integer code;

  ErrorCodes(Integer code) {
    this.code = code;
  }

  public Integer getCode() {
    return code;
  }
}
